spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/baegopang
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  autoconfigure:
    exclude:
      - org.springframework.ai.model.google.genai.autoconfigure.chat.GoogleGenAiChatAutoConfiguration

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none   # Flyway 쓰면 none(또는 validate) 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true